# Generated by Django 4.1.5 on 2023-03-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_house', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.AddField(
            model_name='page',
            name='content1',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='page',
            name='content2',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='page',
            name='prompt',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
